export const profileDatabase = [
  // {
  //   name: "Rick Sanchez",
  //   age: 70,
  //   location: "Earth (C-137)",
  //   status: "Alive",
  //   image: "assets/rick-sanchez.webp",
  //   pageUrl: "rick.html",
  // },
  // {
  //   name: "Diane Sanchez",
  //   age: 35,
  //   location: "Earth (C-137)",
  //   status: "Deceased",
  //   image: "assets/diane-sanchez.webp",
  //   pageUrl: "diane.html",
  // },
  // {
  //   name: "Morty Smith",
  //   age: 14,
  //   location: "Earth (C-137)",
  //   status: "Alive",
  //   image: "assets/morty-smith.webp",
  //   pageUrl: "morty.html",
  // },
  // {
  //   name: "Summer Smith",
  //   age: 17,
  //   location: "Earth (C-137)",
  //   status: "Alive",
  //   image: "assets/summer-smith.webp",
  //   pageUrl: "summer.html",
  // },
  // {
  //   name: "Beth Smith",
  //   age: 34,
  //   location: "Earth (C-137)",
  //   status: "Alive",
  //   image: "assets/beth-smith.webp",
  //   pageUrl: "beth.html",
  // },
  // {
  //   name: "Jerry Smith",
  //   age: 34,
  //   location: "Earth (C-137)",
  //   status: "Alive",
  //   image: "assets/jerry-smith.webp",
  //   pageUrl: "jerry.html",
  // },
];
